# -*- coding: utf-8 -*-
"""LV3_finalproject_OmarHaggag_ DECI4-S-416716.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BikR1QF--iSOdqUHg0oz0Nf8WHvuc8q

**-EDA**

**-Calling used libraries**
"""

import pandas as pd
import requests

"""**-Url Of the API**"""

url="https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"

response = requests.get(url)
data = response.json()

"""**Transforming API URL into a database or DataFrame**"""

df = pd.DataFrame(data['items'])

"""**-Renaming columns**"""

df = df.rename(columns={
    'stargazers_count': 'stars',
    'forks_count': 'forks',
    'watchers_count': 'watchers',
    'open_issues_count': 'open_issues',
    'updated_at':'updated_date',
    'created_at':'created_date'
})

"""**-Needed Columns in Analysis**"""

columns_to_display = [
    'name', 'owner', 'language', 'stars', 'forks',
    'watchers', 'open_issues', 'created_date', 'updated_date', 'license'
]

df=df[columns_to_display]

"""**Note : that piece of code has been got by research  not from the provided content over the dashboard as there was a duplicate for each single column**"""

df = df.loc[:, ~df.columns.duplicated()]

"""**First EDA Step : Exploring the data**

**Displaying First few rows in the DataFrame**
"""

df.head()

df.shape

df.describe()

df.info()

"""**Extracting the Data from the columns of owner and licsnse from the lists they were in**"""

df['owner'] = df['owner'].str['login']
df['license'] = df['license'].str['key']

"""**Second EDA step : Cleaning The Data from null values and duplicates**"""

df.isnull().sum()

df.duplicated().sum()

"""**filling null values by custom values**"""

df['license']=df['license'].fillna('No License')

df['language']=df['language'].fillna('Unknown Language')

"""**Checking Data After being cleaned**"""

df.isnull().sum()

df.duplicated().sum()

df['created_date']=pd.to_datetime(df['created_date'])

df['updated_date']=pd.to_datetime(df['updated_date'])

"""**-Data After being cleaned**"""

df.head()

"""**saving The data into csv file **"""

df.to_csv('github_projects.csv',index=False)

import sqlite3

"""**Creating sql DataBase after calling sqlite3 library**"""

# Commented out IPython magic to ensure Python compatibility.
!pip install ipython-sql==0.5.0 prettytable==3.9.0
# %load_ext sql
# %config SqlMagic.style = 'PLAIN_COLUMNS'
# %sql sqlite:///Repositories.db

"""**Connecting csv File into sql database , creating table named Repositories as required**"""

conn = sqlite3.connect('/content/Repositories.db')
df = pd.read_csv('github_projects.csv')
df.to_sql('Repositories', con=conn,if_exists='replace', index=False)
query = 'SELECT * FROM Repositories'
Repositories = pd.read_sql(query, con=conn)

"""**sorting Repositories with stars greater than 10000 stars in descending order**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM Repositories
# WHERE stars > 10000
# ORDER BY stars DESC;

"""**Using like command to get the nearest name containig same world**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM Repositories
# WHERE name LIKE "%Machine%";

"""**Using logic operaters like and , or**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM Repositories
# WHERE (language='Python'AND license='mit');

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM Repositories
# WHERE (watchers < 5000 OR owner Like "%so%" )
# ORDER BY watchers DESC;

"""**Displaying top 10 Repositories according to the number of stars**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM Repositories
# ORDER BY stars DESC
# LIMIT 10;

"""**(Aggregate Functions)**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT count(*) AS "Total_number_of_repositories" FROM Repositories ;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT AVG(stars) AS "AVG_number_of_Stars" FROM Repositories ;

"""**Grouping function**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT language , count(*) AS "Total_number_of_repositories" FROM Repositories
# GROUP BY language
# Having count(*) > 5 ;

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/github_projects.csv")

df.head()

df.info()

"""**Fixing the inconsistent Data Values**"""

df['updated_date']=pd.to_datetime(df['updated_date'])

df['created_date']=pd.to_datetime(df['created_date'])

"""**Final EDAStep : Data visualization**"""

Top_Popular_Repository = df.sort_values(by='watchers', ascending=False).head(5)
plt.figure(figsize=(9, 5))
plt.bar(Top_Popular_Repository['name'], Top_Popular_Repository['watchers'])
plt.xlabel('Repository Name')
plt.ylabel('Watchers')
plt.title('Top 5 Most Popular Repositories')

df['created_date'] = pd.to_datetime(df['created_date'])
df['creation_year'] = df['created_date'].dt.year
trend_data = df.groupby('creation_year').size()
plt.figure(figsize=(10, 5))
trend_data.plot(kind='line')
plt.xlabel('Creation Year')
plt.ylabel('Number of Repositories Created')
plt.title('Repository Creation Trends Over Time')
plt.show()

"""**Ethical Reflection :**

**1.Why is it important to verify data collected from public APIs?**
**Answer: Verifying public API data: It ensures reliability and catches errors or unexpected changes before they skew your project.**

**2.Why should data analysts document the source of their data?**
**Answer:Documenting data sources: It builds trust, proves credibility, and allows others to trace and reproduce your work.**

**3.How can missing or inaccurate data affect data analysis and decision-making**
**Answer:Impact of missing/inaccurate data: It distorts calculations and can lead to poor decision-making based on flawed conclusions.**
"""